version: '3.8'

services:
  vpn:
    build: .
    container_name: myvpn
    restart: unless-stopped
    ports:
      - "44344:44344"
    volumes:
      - ./config.json:/opt/myvpn/config.json:ro
    environment:
      - TZ=Asia/Shanghai
